if(NOT DEFINED METADATA_FILE OR NOT DEFINED SOURCE_FILE OR NOT DEFINED KCM_METADATA_FILE OR NOT DEFINED KCM_SOURCE_FILE OR NOT DEFINED EXPECTED_PLUGIN_ID)
    message(FATAL_ERROR "usage: cmake -DMETADATA_FILE=<file> -DSOURCE_FILE=<file> -DKCM_METADATA_FILE=<file> -DKCM_SOURCE_FILE=<file> -DEXPECTED_PLUGIN_ID=<id> -P validate-metadata.cmake")
endif()

file(READ "${METADATA_FILE}" METADATA)
file(READ "${SOURCE_FILE}" SOURCE)
file(READ "${KCM_METADATA_FILE}" KCM_METADATA)
file(READ "${KCM_SOURCE_FILE}" KCM_SOURCE)

set(REQUIRED_FIELDS Id Name Description Icon License EnabledByDefault)
foreach(FIELD IN LISTS REQUIRED_FIELDS)
    string(JSON VALUE ERROR_VARIABLE ERROR GET "${METADATA}" "KPlugin" "${FIELD}")
    if(ERROR)
        message(FATAL_ERROR "metadata validation failed: KPlugin/${FIELD} not readable: ${ERROR}")
    endif()
    if(FIELD STREQUAL "EnabledByDefault")
        if(VALUE)
            message(FATAL_ERROR "metadata validation failed: KPlugin/EnabledByDefault must be false, got '${VALUE}'")
        endif()
    elseif(VALUE STREQUAL "")
        message(FATAL_ERROR "metadata validation failed: KPlugin/${FIELD} is empty")
    endif()
endforeach()

string(JSON PLUGIN_ID ERROR_VARIABLE ERROR GET "${METADATA}" "KPlugin" "Id")
if(ERROR OR NOT PLUGIN_ID STREQUAL EXPECTED_PLUGIN_ID)
    message(FATAL_ERROR "metadata validation failed: KPlugin/Id '${PLUGIN_ID}' does not match expected '${EXPECTED_PLUGIN_ID}'")
endif()

string(JSON CONFIG_MODULE ERROR_VARIABLE ERROR GET "${METADATA}" "X-KDE-ConfigModule")
if(ERROR OR NOT CONFIG_MODULE STREQUAL "plasma-auto-tiler-active-border_config")
    message(FATAL_ERROR "metadata validation failed: X-KDE-ConfigModule must route to the native KCM plugin")
endif()

set(REQUIRED_KCM_FIELDS Id Name Description Icon License)
foreach(FIELD IN LISTS REQUIRED_KCM_FIELDS)
    string(JSON VALUE ERROR_VARIABLE ERROR GET "${KCM_METADATA}" "KPlugin" "${FIELD}")
    if(ERROR OR VALUE STREQUAL "")
        message(FATAL_ERROR "KCM metadata validation failed: KPlugin/${FIELD} is missing or empty")
    endif()
endforeach()

string(JSON KCM_ID ERROR_VARIABLE ERROR GET "${KCM_METADATA}" "KPlugin" "Id")
if(ERROR OR NOT KCM_ID STREQUAL "plasma-auto-tiler-active-border_config")
    message(FATAL_ERROR "KCM metadata validation failed: KPlugin/Id must match the configured module plugin")
endif()

string(FIND "${SOURCE}" "KWIN_EFFECT_FACTORY" FACTORY_POS)
if(FACTORY_POS EQUAL -1)
    message(FATAL_ERROR "factory validation failed: KWIN_EFFECT_FACTORY macro not found in ${SOURCE_FILE}")
endif()
string(FIND "${SOURCE}" "ActiveWindowBorderEffect" CLASS_POS)
if(CLASS_POS EQUAL -1)
    message(FATAL_ERROR "factory validation failed: ActiveWindowBorderEffect not found in ${SOURCE_FILE}")
endif()
string(FIND "${SOURCE}" "metadata.json" METADATA_REF_POS)
if(METADATA_REF_POS EQUAL -1)
    message(FATAL_ERROR "factory validation failed: metadata.json reference not found in ${SOURCE_FILE}")
endif()
string(FIND "${KCM_SOURCE}" "K_PLUGIN_CLASS_WITH_JSON" KCM_FACTORY_POS)
if(KCM_FACTORY_POS EQUAL -1)
    message(FATAL_ERROR "KCM factory validation failed: K_PLUGIN_CLASS_WITH_JSON macro not found in ${KCM_SOURCE_FILE}")
endif()
string(FIND "${KCM_SOURCE}" "activeborderconfig_module.json" KCM_METADATA_REF_POS)
if(KCM_METADATA_REF_POS EQUAL -1)
    message(FATAL_ERROR "KCM factory validation failed: embedded metadata reference not found in ${KCM_SOURCE_FILE}")
endif()

message(STATUS "metadata/factory validation passed for ${METADATA_FILE} and ${KCM_METADATA_FILE}")
