if(NOT DEFINED METADATA_FILE OR NOT DEFINED SOURCE_FILE OR NOT DEFINED KCM_METADATA_FILE OR NOT DEFINED KCM_SOURCE_FILE OR NOT DEFINED EXPECTED_PLUGIN_ID)
    message(FATAL_ERROR "usage: cmake -DMETADATA_FILE=<file> -DSOURCE_FILE=<file> -DKCM_METADATA_FILE=<file> -DKCM_SOURCE_FILE=<file> -DEXPECTED_PLUGIN_ID=<id> -P validate-metadata.cmake")
endif()
if(NOT DEFINED GROUP_HEADER OR NOT DEFINED GROUP_IMPL OR NOT DEFINED GROUP_LOGIC OR NOT DEFINED GROUP_TEST)
    message(FATAL_ERROR "usage: cmake -DGROUP_HEADER=<file> -DGROUP_IMPL=<file> -DGROUP_LOGIC=<file> -DGROUP_TEST=<file> -P validate-metadata.cmake")
endif()
if(NOT DEFINED GROUP_FFI OR NOT DEFINED GROUP_RUST)
    message(FATAL_ERROR "usage: cmake -DGROUP_FFI=<file> -DGROUP_RUST=<file> -P validate-metadata.cmake")
endif()
if(NOT DEFINED DRAG_HEADER OR NOT DEFINED DRAG_IMPL OR NOT DEFINED DRAG_FFI OR NOT DEFINED DRAG_RUST)
    message(FATAL_ERROR "usage: cmake -DDRAG_HEADER=<file> -DDRAG_IMPL=<file> -DDRAG_FFI=<file> -DDRAG_RUST=<file> -P validate-metadata.cmake")
endif()

file(READ "${METADATA_FILE}" METADATA)
file(READ "${SOURCE_FILE}" SOURCE)
file(READ "${KCM_METADATA_FILE}" KCM_METADATA)
file(READ "${KCM_SOURCE_FILE}" KCM_SOURCE)

set(REQUIRED_FIELDS Id Name Description Icon License EnabledByDefault)
foreach(FIELD IN LISTS REQUIRED_FIELDS)
    string(JSON VALUE ERROR_VARIABLE ERROR GET "${METADATA}" "KPlugin" "${FIELD}")
    if(ERROR)
        message(FATAL_ERROR "metadata validation failed: KPlugin/${FIELD} not readable: ${ERROR}")
    endif()
    if(FIELD STREQUAL "EnabledByDefault")
        if(VALUE)
            message(FATAL_ERROR "metadata validation failed: KPlugin/EnabledByDefault must be false, got '${VALUE}'")
        endif()
    elseif(VALUE STREQUAL "")
        message(FATAL_ERROR "metadata validation failed: KPlugin/${FIELD} is empty")
    endif()
endforeach()

string(JSON PLUGIN_ID ERROR_VARIABLE ERROR GET "${METADATA}" "KPlugin" "Id")
if(ERROR OR NOT PLUGIN_ID STREQUAL EXPECTED_PLUGIN_ID)
    message(FATAL_ERROR "metadata validation failed: KPlugin/Id '${PLUGIN_ID}' does not match expected '${EXPECTED_PLUGIN_ID}'")
endif()

# One surviving plugin visibly branded Plasma Auto Tiler; the stable plugin,
# KCM, and config identifiers never change.
string(JSON PLUGIN_NAME ERROR_VARIABLE ERROR GET "${METADATA}" "KPlugin" "Name")
if(ERROR OR NOT PLUGIN_NAME STREQUAL "Plasma Auto Tiler")
    message(FATAL_ERROR "metadata validation failed: KPlugin/Name '${PLUGIN_NAME}' must be the visible 'Plasma Auto Tiler' brand")
endif()
if(PLUGIN_ID STREQUAL "plasma-auto-tiler-drag-oracle")
    message(FATAL_ERROR "metadata validation failed: the standalone drag-oracle plugin id must not survive consolidation")
endif()

string(JSON CONFIG_MODULE ERROR_VARIABLE ERROR GET "${METADATA}" "X-KDE-ConfigModule")
if(ERROR OR NOT CONFIG_MODULE STREQUAL "plasma-auto-tiler-active-border_config")
    message(FATAL_ERROR "metadata validation failed: X-KDE-ConfigModule must route to the native KCM plugin")
endif()

set(REQUIRED_KCM_FIELDS Id Name Description Icon License)
foreach(FIELD IN LISTS REQUIRED_KCM_FIELDS)
    string(JSON VALUE ERROR_VARIABLE ERROR GET "${KCM_METADATA}" "KPlugin" "${FIELD}")
    if(ERROR OR VALUE STREQUAL "")
        message(FATAL_ERROR "KCM metadata validation failed: KPlugin/${FIELD} is missing or empty")
    endif()
endforeach()

string(JSON KCM_ID ERROR_VARIABLE ERROR GET "${KCM_METADATA}" "KPlugin" "Id")
if(ERROR OR NOT KCM_ID STREQUAL "plasma-auto-tiler-active-border_config")
    message(FATAL_ERROR "KCM metadata validation failed: KPlugin/Id must match the configured module plugin")
endif()

string(FIND "${SOURCE}" "KWIN_EFFECT_FACTORY" FACTORY_POS)
if(FACTORY_POS EQUAL -1)
    message(FATAL_ERROR "factory validation failed: KWIN_EFFECT_FACTORY macro not found in ${SOURCE_FILE}")
endif()
string(FIND "${SOURCE}" "ActiveWindowBorderEffect" CLASS_POS)
if(CLASS_POS EQUAL -1)
    message(FATAL_ERROR "factory validation failed: ActiveWindowBorderEffect not found in ${SOURCE_FILE}")
endif()
string(FIND "${SOURCE}" "metadata.json" METADATA_REF_POS)
if(METADATA_REF_POS EQUAL -1)
    message(FATAL_ERROR "factory validation failed: metadata.json reference not found in ${SOURCE_FILE}")
endif()
string(FIND "${KCM_SOURCE}" "K_PLUGIN_CLASS_WITH_JSON" KCM_FACTORY_POS)
if(KCM_FACTORY_POS EQUAL -1)
    message(FATAL_ERROR "KCM factory validation failed: K_PLUGIN_CLASS_WITH_JSON macro not found in ${KCM_SOURCE_FILE}")
endif()
string(FIND "${KCM_SOURCE}" "activeborderconfig_module.json" KCM_METADATA_REF_POS)
if(KCM_METADATA_REF_POS EQUAL -1)
    message(FATAL_ERROR "KCM factory validation failed: embedded metadata reference not found in ${KCM_SOURCE_FILE}")
endif()

# Temporary active-group highlight: effect-owned writable endpoint plus a
# second outline, gated on passive Meta observation. The generic /Effects bus
# cannot dispatch effect-defined setters, so the effect must own its
# well-known service/path/interface exactly like the drag oracle. Group
# policy (payload parsing, ordering, focus, visibility, state) lives in the
# std-only Rust staticlib behind a minimal POD C ABI; C++ is limited to the
# QObject/D-Bus QString-to-UTF8 boundary, Qt signal POD observation and
# native identity, plus effect lifetime/repaint/render.
file(READ "${GROUP_HEADER}" GROUP_HEADER_TEXT)
file(READ "${GROUP_IMPL}" GROUP_IMPL_TEXT)
file(READ "${GROUP_LOGIC}" GROUP_LOGIC_TEXT)
file(READ "${GROUP_TEST}" GROUP_TEST_TEXT)
file(READ "${GROUP_FFI}" GROUP_FFI_TEXT)
file(READ "${GROUP_RUST}" GROUP_RUST_TEXT)

# FFI hygiene: no Qt/KWin type crosses into Rust.
foreach(GROUP_FORBIDDEN_FFI "QString" "QRect" "QUuid" "EffectWindow" "qreal" "QByteArray" "QJson" "QObject")
    string(FIND "${GROUP_FFI_TEXT}" "${GROUP_FORBIDDEN_FFI}" GROUP_FFI_FORBIDDEN_POS)
    if(NOT GROUP_FFI_FORBIDDEN_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight FFI validation failed: '${GROUP_FORBIDDEN_FFI}' must not cross into Rust")
    endif()
endforeach()
foreach(GROUP_SYMBOL "group_highlight_state_init" "group_highlight_apply" "group_highlight_clear" "group_highlight_focus_matches" "group_highlight_focus_eligible" "group_highlight_is_visible" "group_highlight_rect" "group_highlight_status" "initial_maximize_state_init" "initial_maximize_apply" "initial_maximize_clear" "initial_maximize_is_confirmed" "initial_maximize_allows_display" "initial_maximize_status")
    string(FIND "${GROUP_FFI_TEXT}" "${GROUP_SYMBOL}" GROUP_FFI_SYMBOL_POS)
    if(GROUP_FFI_SYMBOL_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight FFI validation failed: '${GROUP_SYMBOL}' missing from FFI header")
    endif()
    string(FIND "${GROUP_RUST_TEXT}" "${GROUP_SYMBOL}" GROUP_RUST_SYMBOL_POS)
    if(GROUP_RUST_SYMBOL_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight FFI validation failed: '${GROUP_SYMBOL}' missing from Rust source")
    endif()
endforeach()
foreach(GROUP_POD "GroupHighlightState" "GroupHighlightRect" "GroupHighlightStatus" "InitialMaximizeState" "InitialMaximizeStatus")
    string(FIND "${GROUP_FFI_TEXT}" "${GROUP_POD}" GROUP_POD_FFI_POS)
    if(GROUP_POD_FFI_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight FFI validation failed: '${GROUP_POD}' missing from FFI header")
    endif()
    string(FIND "${GROUP_RUST_TEXT}" "${GROUP_POD}" GROUP_POD_RUST_POS)
    if(GROUP_POD_RUST_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight FFI validation failed: '${GROUP_POD}' missing from Rust source")
    endif()
endforeach()

# Rust ownership: every export guards against unwinding; the payload
# contract carries correlation/revision/focused_window with the JSON-safe
# revision bound and the carried-geometry bound.
string(REGEX MATCHALL "catch_unwind" GROUP_UNWIND_MATCHES "${GROUP_RUST_TEXT}")
list(LENGTH GROUP_UNWIND_MATCHES GROUP_UNWIND_COUNT)
if(GROUP_UNWIND_COUNT LESS 14)
    message(FATAL_ERROR "group-highlight Rust validation failed: expected catch_unwind on every export (14), found ${GROUP_UNWIND_COUNT}")
endif()
foreach(GROUP_REQUIRED "correlation" "revision" "focused_window" "9007199254740991" "16384" "order_initialized" "active_window" "maximize_mode")
    string(FIND "${GROUP_RUST_TEXT}" "${GROUP_REQUIRED}" GROUP_REQUIRED_POS)
    if(GROUP_REQUIRED_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight Rust validation failed: '${GROUP_REQUIRED}' not found in policy source")
    endif()
endforeach()

# Policy must not live in C++ anymore: no QString JSON parsing, ordering,
# or focus/visibility policy beside the FFI call sites.
foreach(GROUP_MOVED "parseGroupHighlightPayload" "acceptGroupHighlightOrder" "ParsedGroupHighlight" "GroupHighlightOrder" "shouldShowGroupHighlight" "groupFocusEligible" "groupFocusMatches" "isGroupEndpointUsable" "QJsonDocument")
    string(FIND "${GROUP_IMPL_TEXT}" "${GROUP_MOVED}" GROUP_MOVED_IMPL_POS)
    if(NOT GROUP_MOVED_IMPL_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight layering validation failed: '${GROUP_MOVED}' must not exist in implementation (policy lives in Rust)")
    endif()
    string(FIND "${GROUP_HEADER_TEXT}" "${GROUP_MOVED}" GROUP_MOVED_HEADER_POS)
    if(NOT GROUP_MOVED_HEADER_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight layering validation failed: '${GROUP_MOVED}' must not exist in header (policy lives in Rust)")
    endif()
    string(FIND "${GROUP_LOGIC_TEXT}" "${GROUP_MOVED}" GROUP_MOVED_LOGIC_POS)
    if(NOT GROUP_MOVED_LOGIC_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight layering validation failed: '${GROUP_MOVED}' must not exist in shared logic (policy lives in Rust)")
    endif()
endforeach()
foreach(GROUP_FFI_USE "group_highlight_state_init" "group_highlight_apply" "group_highlight_clear" "group_highlight_is_visible" "group_highlight_focus_eligible" "group_highlight_rect" "group_highlight_status" "initial_maximize_state_init" "initial_maximize_apply" "initial_maximize_clear" "initial_maximize_is_confirmed" "initial_maximize_allows_display")
    string(FIND "${GROUP_IMPL_TEXT}" "${GROUP_FFI_USE}" GROUP_FFI_USE_POS)
    if(GROUP_FFI_USE_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight wiring validation failed: '${GROUP_FFI_USE}' not found in implementation")
    endif()
endforeach()
foreach(GROUP_STATE_MEMBER "GroupHighlightState" "m_groupState")
    string(FIND "${GROUP_HEADER_TEXT}" "${GROUP_STATE_MEMBER}" GROUP_STATE_MEMBER_POS)
    if(GROUP_STATE_MEMBER_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight wiring validation failed: '${GROUP_STATE_MEMBER}' missing in header (effect holds Rust policy state by value)")
    endif()
endforeach()

string(REGEX MATCHALL "Q_SCRIPTABLE" GROUP_SCRIPTABLE_MATCHES "${GROUP_IMPL_TEXT}")
list(LENGTH GROUP_SCRIPTABLE_MATCHES GROUP_SCRIPTABLE_COUNT)
if(NOT GROUP_SCRIPTABLE_COUNT EQUAL 7)
    message(FATAL_ERROR "group-highlight D-Bus validation failed: expected group setter, group clear, read-only status, initial set/clear, the initial epoch getter, plus the folded LastVerdict Q_SCRIPTABLE methods, found ${GROUP_SCRIPTABLE_COUNT}")
endif()
foreach(GROUP_METHOD SetGroupHighlight ClearGroupHighlight GetGroupHighlightStatus SetInitialMaximizeState ClearInitialMaximizeState GetInitialMaximizeEpoch LastVerdict)
    string(FIND "${GROUP_IMPL_TEXT}" "${GROUP_METHOD}" GROUP_METHOD_POS)
    if(GROUP_METHOD_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight D-Bus validation failed: ${GROUP_METHOD} not found")
    endif()
endforeach()
foreach(GROUP_ENDPOINT "org.plasmaautotiler.ActiveBorder" "/org/plasmaautotiler/ActiveBorder" "org.plasmaautotiler.ActiveBorder1" "ExportScriptableContents" "sessionBus" "unregisterObject" "unregisterService")
    string(FIND "${GROUP_IMPL_TEXT}" "${GROUP_ENDPOINT}" GROUP_ENDPOINT_POS)
    if(GROUP_ENDPOINT_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight endpoint validation failed: '${GROUP_ENDPOINT}' not found")
    endif()
endforeach()
string(FIND "${GROUP_IMPL_TEXT}" "/Effects" GROUP_EFFECTS_POS)
if(NOT GROUP_EFFECTS_POS EQUAL -1)
    message(FATAL_ERROR "group-highlight transport validation failed: /Effects must never be used for effect-defined setters")
endif()

# Exactly two auto-lifetime outlines: the preserved active border plus the
# group union outline. No custom scene rendering.
string(REGEX MATCHALL "OutlinedBorderItem" GROUP_OUTLINE_MATCHES "${GROUP_HEADER_TEXT}")
list(LENGTH GROUP_OUTLINE_MATCHES GROUP_OUTLINE_COUNT)
if(NOT GROUP_OUTLINE_COUNT EQUAL 2)
    message(FATAL_ERROR "group-highlight outline validation failed: expected exactly two OutlinedBorderItem members, found ${GROUP_OUTLINE_COUNT}")
endif()
foreach(GROUP_MEMBER "m_borderItem" "m_groupItem")
    string(FIND "${GROUP_HEADER_TEXT}" "${GROUP_MEMBER}" GROUP_MEMBER_POS)
    if(GROUP_MEMBER_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight outline validation failed: ${GROUP_MEMBER} missing in header")
    endif()
endforeach()
foreach(GROUP_RENDER "m_groupItem.setParentItem" "m_groupItem.setOutline" "m_groupItem.setInnerRect" "m_groupItem.setVisible" "group_highlight_rect")
    string(FIND "${GROUP_IMPL_TEXT}" "${GROUP_RENDER}" GROUP_RENDER_POS)
    if(GROUP_RENDER_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight rendering validation failed: '${GROUP_RENDER}' not found")
    endif()
endforeach()

# Passive Meta observation only: mouseChanged plus MetaModifier, unknown
# before the first signal. No polling, timers, grabs, interception,
# filters, shortcut mutation, or paint hooks. Policy predicates arrive via
# the Rust FFI; the QString-to-UTF8 boundary plus native identity stay here.
foreach(GROUP_PASSIVE "mouseChanged" "MetaModifier" "m_firstMouseSeen" "m_metaHeld" "toUtf8" "internalId" "group_highlight_apply" "group_highlight_is_visible" "group_highlight_focus_eligible")
    string(FIND "${GROUP_IMPL_TEXT}" "${GROUP_PASSIVE}" GROUP_PASSIVE_POS)
    if(GROUP_PASSIVE_POS EQUAL -1)
        string(FIND "${GROUP_LOGIC_TEXT}" "${GROUP_PASSIVE}" GROUP_PASSIVE_LOGIC_POS)
        if(GROUP_PASSIVE_LOGIC_POS EQUAL -1)
            message(FATAL_ERROR "group-highlight visibility validation failed: '${GROUP_PASSIVE}' not found")
        endif()
    endif()
endforeach()
# Focus activation must clear the old group immediately; fullscreen/minimized
# transitions must update visibility via the owned tracked signals; the
# accepted payload's focused_window must bind to the live active internalId;
# registration failure must fail closed with no retry. The initial handoff
# additionally pins a per-instance epoch: deleted/closed windows clear its
# authority and only the live epoch authorizes.
foreach(GROUP_BINDING "m_groupDbusAvailable" "internalId" "group_highlight_focus_matches" "group_highlight_focus_eligible" "windowClosed" "clearGroupHighlight" "GetInitialMaximizeEpoch" "createUuid" "m_initialEpoch" "clearInitialGate")
    string(FIND "${GROUP_IMPL_TEXT}" "${GROUP_BINDING}" GROUP_BINDING_POS)
    if(GROUP_BINDING_POS EQUAL -1)
        string(FIND "${GROUP_RUST_TEXT}" "${GROUP_BINDING}" GROUP_BINDING_RUST_POS)
        if(GROUP_BINDING_RUST_POS EQUAL -1)
            message(FATAL_ERROR "group-highlight focus/endpoint validation failed: '${GROUP_BINDING}' not found")
        endif()
    endif()
endforeach()
foreach(GROUP_VIS "minimizedChanged" "windowFullScreenChanged" "updateGroupVisibility")
    string(FIND "${GROUP_IMPL_TEXT}" "${GROUP_VIS}" GROUP_VIS_POS)
    if(GROUP_VIS_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight lifecycle validation failed: '${GROUP_VIS}' not found")
    endif()
endforeach()
string(FIND "${GROUP_IMPL_TEXT}" "registerService" GROUP_REG_POS)
if(GROUP_REG_POS EQUAL -1)
    message(FATAL_ERROR "group-highlight endpoint validation failed: registerService gate missing")
endif()
foreach(GROUP_FORBIDDEN "QTimer" "singleShot" "startMousePolling" "grabMouse" "grabKeyboard" "installEventFilter" "installSceneFilter" "registerShortcut" "registerPropertyType" "paintWindow" "drawWindow" "prePaintScreen" "postPaintScreen" "startTimer")
    string(FIND "${GROUP_IMPL_TEXT}" "${GROUP_FORBIDDEN}" GROUP_FORBIDDEN_POS)
    if(NOT GROUP_FORBIDDEN_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight passivity validation failed: '${GROUP_FORBIDDEN}' must not exist in implementation")
    endif()
    string(FIND "${GROUP_HEADER_TEXT}" "${GROUP_FORBIDDEN}" GROUP_FORBIDDEN_HEADER_POS)
    if(NOT GROUP_FORBIDDEN_HEADER_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight passivity validation failed: '${GROUP_FORBIDDEN}' must not exist in header")
    endif()
endforeach()

# Offline state coverage must exist through the Rust FFI and must poison the
# session bus before any Qt setup, mirroring the native KCM tests.
foreach(GROUP_COVERAGE "group_highlight_apply" "group_highlight_clear" "group_highlight_is_visible" "group_highlight_focus_eligible" "group_highlight_focus_matches" "group_highlight_rect" "group_highlight_status" "initial_maximize_apply" "initial_maximize_clear" "initial_maximize_is_confirmed" "initial_maximize_allows_display" "DBUS_SESSION_BUS_ADDRESS")
    string(FIND "${GROUP_TEST_TEXT}" "${GROUP_COVERAGE}" GROUP_COVERAGE_POS)
    if(GROUP_COVERAGE_POS EQUAL -1)
        message(FATAL_ERROR "group-highlight test validation failed: '${GROUP_COVERAGE}' not covered by the offline test")
    endif()
endforeach()

# Folded Slice 1 drag oracle (essential validation, formerly
# validate-dragoracle.cmake): the survivor hosts the read-only LastVerdict
# endpoint with process-static verdict storage served via copy, observes only
# interactive drag start/finish geometry, and keeps Qt/KWin types out of Rust.
file(READ "${DRAG_HEADER}" DRAG_HEADER_TEXT)
file(READ "${DRAG_IMPL}" DRAG_IMPL_TEXT)
file(READ "${DRAG_FFI}" DRAG_FFI_TEXT)
file(READ "${DRAG_RUST}" DRAG_RUST_TEXT)

foreach(DRAG_ENDPOINT "org.plasmaautotiler.DragOracle" "/org/plasmaautotiler/DragOracle" "org.plasmaautotiler.DragOracle1" "LastVerdict" "ExportScriptableContents" "unregisterObject" "unregisterService")
    string(FIND "${DRAG_IMPL_TEXT}" "${DRAG_ENDPOINT}" DRAG_ENDPOINT_POS)
    if(DRAG_ENDPOINT_POS EQUAL -1)
        message(FATAL_ERROR "drag-oracle endpoint validation failed: '${DRAG_ENDPOINT}' not found in survivor implementation")
    endif()
endforeach()
foreach(DRAG_SIGNAL "windowStartUserMovedResized" "windowFinishUserMovedResized" "moveResizeGeometry" "drag_oracle_record" "drag_oracle_last_copy" "oracleMoveResizeRect")
    string(FIND "${DRAG_IMPL_TEXT}" "${DRAG_SIGNAL}" DRAG_SIGNAL_POS)
    if(DRAG_SIGNAL_POS EQUAL -1)
        message(FATAL_ERROR "drag-oracle observation validation failed: '${DRAG_SIGNAL}' not found in survivor implementation")
    endif()
endforeach()
foreach(DRAG_FORBIDDEN_FFI "QString" "QRect" "QUuid" "EffectWindow" "qreal" "QByteArray" "QJson" "QObject")
    string(FIND "${DRAG_FFI_TEXT}" "${DRAG_FORBIDDEN_FFI}" DRAG_FFI_FORBIDDEN_POS)
    if(NOT DRAG_FFI_FORBIDDEN_POS EQUAL -1)
        message(FATAL_ERROR "drag-oracle FFI validation failed: '${DRAG_FORBIDDEN_FFI}' must not cross into Rust")
    endif()
endforeach()
foreach(DRAG_SYMBOL "drag_oracle_record" "drag_oracle_last" "drag_oracle_last_copy")
    string(FIND "${DRAG_FFI_TEXT}" "${DRAG_SYMBOL}" DRAG_FFI_SYMBOL_POS)
    if(DRAG_FFI_SYMBOL_POS EQUAL -1)
        message(FATAL_ERROR "drag-oracle FFI validation failed: '${DRAG_SYMBOL}' missing from FFI header")
    endif()
    string(FIND "${DRAG_RUST_TEXT}" "${DRAG_SYMBOL}" DRAG_RUST_SYMBOL_POS)
    if(DRAG_RUST_SYMBOL_POS EQUAL -1)
        message(FATAL_ERROR "drag-oracle FFI validation failed: '${DRAG_SYMBOL}' missing from Rust source")
    endif()
endforeach()
# The POD rect crosses the ABI by repr(C) layout: DragOracleRect in C++,
# DragRect in Rust. Both names must exist on their own side.
string(FIND "${DRAG_FFI_TEXT}" "DragOracleRect" DRAG_POD_FFI_POS)
if(DRAG_POD_FFI_POS EQUAL -1)
    message(FATAL_ERROR "drag-oracle FFI validation failed: 'DragOracleRect' missing from FFI header")
endif()
string(FIND "${DRAG_RUST_TEXT}" "DragRect" DRAG_POD_RUST_POS)
if(DRAG_POD_RUST_POS EQUAL -1)
    message(FATAL_ERROR "drag-oracle FFI validation failed: 'DragRect' missing from Rust source")
endif()
foreach(DRAG_REQUIRED "catch_unwind" "correlation" "cancelled" "finalRect" "windowIdentity" "no-change" "geometry-invalid")
    string(FIND "${DRAG_RUST_TEXT}" "${DRAG_REQUIRED}" DRAG_REQUIRED_POS)
    if(DRAG_REQUIRED_POS EQUAL -1)
        message(FATAL_ERROR "drag-oracle Rust validation failed: '${DRAG_REQUIRED}' not found in oracle source")
    endif()
endforeach()
foreach(DRAG_VAGUE "\"reason\":\"failure\"" "\"reason\":\"error\"" "\"reason\":\"unknown\"")
    string(FIND "${DRAG_RUST_TEXT}" "${DRAG_VAGUE}" DRAG_VAGUE_POS)
    if(NOT DRAG_VAGUE_POS EQUAL -1)
        message(FATAL_ERROR "drag-oracle Rust validation failed: oracle must not carry vague failure token ${DRAG_VAGUE}")
    endif()
endforeach()

message(STATUS "metadata/factory validation passed for ${METADATA_FILE} and ${KCM_METADATA_FILE}")
